--- 
global: 
  owner: siddharth.mishra@yash.com
  qsname: template-check
  regions: 
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests: 
  taskcat-test1: 
    parameter_input: input.json
    regions: 
      - us-east-1
      - us-east-2
      - us-west-2
      - ap-south-1
    template_file: ec2.template
